import AppKit
import QuickLook
import SwiftUI
import NtfyKit

/// The detail column: the single selected message, a summary when several
/// rows are selected, or an empty-state placeholder when none are.
struct HistoryDetailView: View {
    @Bindable var viewModel: HistoryViewModel

    var body: some View {
        Group {
            let selected = viewModel.messages.filter { viewModel.selection.contains($0.id) }
            if selected.isEmpty {
                HistoryStatusView(systemImage: "envelope", title: "No Message Selected",
                                  message: "Select a message to see its contents.")
            } else if selected.count == 1 {
                MessageDetailContent(snapshot: selected[0], viewModel: viewModel)
            } else {
                MultiSelectionSummary(snapshots: selected, viewModel: viewModel)
            }
        }
        .frame(minWidth: 320)
    }
}

private struct MessageDetailContent: View {
    let snapshot: MessageSnapshot
    let viewModel: HistoryViewModel
    @State private var quickLookURL: URL?

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                header
                bodyText
                    .textSelection(.enabled)
                if !snapshot.tags.isEmpty {
                    tagRow
                }
                if let attachmentURL = localAttachmentURL {
                    Button {
                        quickLookURL = attachmentURL
                    } label: {
                        Label("Preview Attachment", systemImage: "eye")
                    }
                }
                if !messageActions.isEmpty {
                    actionButtons
                }
                Spacer(minLength: 0)
            }
            .padding()
            .frame(maxWidth: .infinity, alignment: .leading)
        }
        .quickLookPreview($quickLookURL)
        .toolbar { toolbarActions }
        .navigationTitle(snapshot.title?.isEmpty == false ? snapshot.title! : snapshot.topic)
        // `AttributedString(markdown:)` can produce a clickable link from
        // the message body with an arbitrary scheme — a path that looks
        // like ordinary framework behavior rather than attacker-controlled
        // input, but the body is exactly that (spec §9). Intercepting
        // `openURL` here routes every link tap in this view, markdown or
        // not, through the same `NtfyURLPolicy` the click/action buttons use,
        // instead of SwiftUI's default handler opening it unchecked.
        .environment(\.openURL, OpenURLAction { url in
            guard let sanitized = NtfyURLPolicy.sanitized(url.absoluteString) else { return .discarded }
            NSWorkspace.shared.open(sanitized)
            return .handled
        })
    }

    private var header: some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(alignment: .firstTextBaseline) {
                Text(snapshot.title?.isEmpty == false ? snapshot.title! : snapshot.topic)
                    .font(.title2.bold())
                Spacer()
                PriorityPill(priority: snapshot.resolvedPriority)
            }
            HStack(spacing: 6) {
                Text(snapshot.topic)
                Text("·")
                Text(snapshot.time, format: .dateTime.year().month().day().hour().minute())
            }
            .font(.caption)
            .foregroundStyle(.secondary)
        }
    }

    /// `AttributedString(markdown:)` throws on malformed input. An ntfy
    /// message body is arbitrary remote input (spec §9), so a publisher that
    /// sends broken markdown must fall back to plain text, never crash the
    /// window or render nothing.
    private var bodyText: Text {
        guard snapshot.isMarkdown else { return Text(snapshot.body) }
        do {
            let attributed = try AttributedString(
                markdown: snapshot.body,
                options: AttributedString.MarkdownParsingOptions(interpretedSyntax: .full))
            return Text(attributed)
        } catch {
            return Text(snapshot.body)
        }
    }

    private var tagRow: some View {
        ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 4) {
                ForEach(snapshot.tags, id: \.self) { TagChip(tag: $0) }
            }
        }
    }

    /// Resolves the attachment's local file for Quick Look, or `nil` when
    /// there is nothing to preview: no attachment, no downloaded file yet
    /// (`localFilename == nil`), or no attachments directory configured
    /// (`HistoryWindowController` was constructed without one).
    ///
    /// The path-component guard mirrors `MessageStore.prune`'s: `localFilename`
    /// is generated by `AttachmentDownloader` today and should already be a
    /// bare component, but a Quick Look preview reading a path this view
    /// builds from server-influenced metadata should not depend on every
    /// future writer of that field getting it right.
    private var localAttachmentURL: URL? {
        guard let filename = snapshot.attachment?.localFilename,
              !filename.isEmpty, !filename.contains("/"), !filename.contains("\\"),
              filename != ".", filename != "..",
              let directory = viewModel.attachmentsDirectory
        else { return nil }
        return directory.appendingPathComponent(filename)
    }

    /// The sanitized, presentable subset of `snapshot.actions` — delegates to
    /// `NotificationDecision.presentableActions`, the one place the
    /// URL-scheme allow-list, HTTP method allow-list, and header deny-list
    /// for a message's action buttons are expressed (spec §9: a message is
    /// attacker-controlled). Reusing it, now that it is public, is what
    /// makes `http` actions safe to offer here too.
    private var messageActions: [PresentableAction] {
        NotificationDecision.presentableActions(from: snapshot.actions)
    }

    private var actionButtons: some View {
        HStack {
            ForEach(messageActions) { action in
                Button(action.title) {
                    Task { await NotificationActionHandler.perform(action) }
                }
            }
        }
    }

    @ToolbarContentBuilder
    private var toolbarActions: some ToolbarContent {
        ToolbarItemGroup {
            Button {
                Task { await viewModel.markRead([snapshot], read: !snapshot.isRead) }
            } label: {
                Label(snapshot.isRead ? "Mark as Unread" : "Mark as Read",
                      systemImage: snapshot.isRead ? "envelope.badge" : "envelope.open")
            }
            .help(snapshot.isRead ? "Mark as Unread" : "Mark as Read")

            Button {
                viewModel.copy([snapshot])
            } label: {
                Label("Copy", systemImage: "doc.on.doc")
            }
            .help("Copy")

            if snapshot.click != nil {
                Button {
                    viewModel.openClickURL(snapshot)
                } label: {
                    Label("Open Link", systemImage: "arrow.up.right.square")
                }
                .help("Open Link")
            }

            Button(role: .destructive) {
                Task { await viewModel.delete([snapshot]) }
            } label: {
                Label("Delete", systemImage: "trash")
            }
            .help("Delete")
        }
    }
}

private struct MultiSelectionSummary: View {
    let snapshots: [MessageSnapshot]
    let viewModel: HistoryViewModel

    var body: some View {
        VStack(spacing: 16) {
            Text("\(snapshots.count) Messages Selected")
                .font(.title3.bold())
            HStack {
                Button("Mark as Read") { Task { await viewModel.markRead(snapshots, read: true) } }
                Button("Mark as Unread") { Task { await viewModel.markRead(snapshots, read: false) } }
                Button("Copy") { viewModel.copy(snapshots) }
                Button("Delete", role: .destructive) { Task { await viewModel.delete(snapshots) } }
            }
        }
        .padding()
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}
